apiVersion: v1
kind: Pod
metadata:
  name: tool
spec:
  containers:
  - name: tool
    image: darumms/msg-cli:latest
    command:
      - /bin/bash
      - "-C"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
